services:
  
  bot:
    build: .
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql_db
    ports:
      - '8001:8001'
    command: sh -c 'python main.py'
    networks:
      - bot_network
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

  redis_tg_bot_db:
    image: redis:alpine
    restart: on-failure
    networks:
      - bot_network
    cpus: '0.5'
    ports:
      - 6379:6379
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD} --save "10" "1" --appendonly no
    volumes:
      - redis_tg_bot_data:/data
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

  arq_high:
    build: .
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql_db
      - REDIS_HOST=redis_tg_bot_db

    networks:
      - bot_network
    command: arq background.high_worker.WorkerSettings
    depends_on:
      - redis_tg_bot_db

  arq_low:
    build: .
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql_db
      - REDIS_HOST=redis_tg_bot_db
    networks:
      - bot_network
    command: arq background.low_worker.WorkerSettings
    depends_on:
      - redis_tg_bot_db

  arq_popular:
    build: .
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=psql_db
      - REDIS_HOST=redis_tg_bot_db
    networks:
      - bot_network
    command: arq background.popular_worker.WorkerSettings
    depends_on:
      - redis_tg_bot_db

  psql_db:
    image: postgres:14
    # restart: always
    networks:
      - bot_network
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Moscow
    cpus: '1.0'
    mem_limit: 2g
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"

networks:
  bot_network:

volumes:
  postgres-data:
  redis_tg_bot_data: