"""message_sendings

Revision ID: 010a0682604b
Revises: 9dc30c7c3c50
Create Date: 2025-07-30 11:55:45.549230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010a0682604b'
down_revision: Union[str, None] = '9dc30c7c3c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_sendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'TEST', 'UPCOMING', 'PROCESSING', 'COMPLETED', 'FAILED', name='messagesendingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('users_to_notify', sa.Integer(), nullable=True),
    sa.Column('users_notified', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_sendings_id'), 'message_sendings', ['id'], unique=False)
    op.create_table('message_sending_butttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_sending_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'DATA', 'URL', 'KEYBOARD', name='messagesendingbuttontype'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['message_sending_id'], ['message_sendings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_sending_butttons_id'), 'message_sending_butttons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sending_butttons_id'), table_name='message_sending_butttons')
    op.drop_table('message_sending_butttons')
    op.drop_index(op.f('ix_message_sendings_id'), table_name='message_sendings')
    op.drop_table('message_sendings')
    # ### end Alembic commands ###
    sa.Enum('CREATED', 'TEST', 'UPCOMING', 'PROCESSING', 'COMPLETED', 'FAILED', name='messagesendingstatus').drop(op.get_bind())
    sa.Enum('TEXT', 'DATA', 'URL', 'KEYBOARD', name='messagesendingbuttontype').drop(op.get_bind())
