"""invited_by_user_user_field

Revision ID: 20a9694c68d1
Revises: fef31fb46def
Create Date: 2025-09-15 19:05:31.458172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a9694c68d1'
down_revision: Union[str, None] = 'fef31fb46def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by_user', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['invited_by_user'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invited_by_user')
    # ### end Alembic commands ###
