"""alter_add_bool_cols_to_channel_link

Revision ID: 6d523db8a4f4
Revises: b740c88f8d8d
Create Date: 2025-06-11 17:39:29.372428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d523db8a4f4'
down_revision: Union[str, None] = 'b740c88f8d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_links', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('channel_links', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_links', 'is_active')
    op.drop_column('channel_links', 'is_admin')
    # ### end Alembic commands ###
