"""popular_product_sale_range

Revision ID: a45012948e17
Revises: 6d523db8a4f4
Create Date: 2025-06-18 14:49:30.883264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45012948e17'
down_revision: Union[str, None] = '6d523db8a4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('popular_product_sale_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_price', sa.Integer(), nullable=True),
    sa.Column('end_price', sa.Integer(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popular_product_sale_ranges_id'), 'popular_product_sale_ranges', ['id'], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(table, [
        {
            'id': 1,
            'start_price': 0,
            'end_price': 2000,
            'coefficient': 0.3,
        },
        {
            'id': 2,
            'start_price': 2000,
            'end_price': 35000,
            'coefficient': 0.25,
        },
        {
            'id': 3,
            'start_price': 35000,
            'end_price': 50000,
            'coefficient': 0.2,
        },
        {
            'id': 4,
            'start_price': 50000,
            'end_price': 80000,
            'coefficient': 0.15,
        },
        {
            'id': 5,
            'start_price': 80000,
            'end_price': 110000,
            'coefficient': 0.1,
        },
        {
            'id': 6,
            'start_price': 110000,
            'end_price': 2147483647,
            'coefficient': 0.07,
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popular_product_sale_ranges_id'), table_name='popular_product_sale_ranges')
    op.drop_table('popular_product_sale_ranges')
    # ### end Alembic commands ###
