"""add_order_price

Revision ID: d4755b08d87b
Revises: 98d8b286dd90
Create Date: 2025-07-08 16:35:02.171349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4755b08d87b'
down_revision: Union[str, None] = '98d8b286dd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
