"""message_sendign image

Revision ID: fef31fb46def
Revises: 010a0682604b
Create Date: 2025-07-30 19:48:42.200703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef31fb46def'
down_revision: Union[str, None] = '010a0682604b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_sendings', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_sendings', 'image')
    # ### end Alembic commands ###
